# Generated by Django 5.0.14 on 2026-09-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_generatedreport_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], max_length=8),
        ),
    ]
