# Generated by Django 5.0.14 on 2026-08-27 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('DISCOVERY', 'Host discovery'), ('PORT_SCAN', 'Port & service scan'), ('FULL', 'Full scan (discovery + ports + OS fingerprint)'), ('WEB', 'Web scan (HTTP/HTTPS service + headers)')], default='FULL', max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('nmap_arguments', models.CharField(default='-sV -O --top-ports 100', max_length=255)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(default='up', max_length=16)),
                ('os_family', models.CharField(blank=True, max_length=128)),
                ('os_accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=32)),
                ('raw_probe_notes', models.TextField(blank=True, help_text='Notes from Scapy SYN/ACK probing')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='scanning.scanjob')),
            ],
            options={
                'unique_together': {('job', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('ip_or_cidr', models.CharField(help_text='e.g. 10.0.0.15, 10.0.0.0/24, or a web hostname like example.com', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scanjob',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='scanning.target'),
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.PositiveIntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=8)),
                ('state', models.CharField(default='open', max_length=16)),
                ('service_name', models.CharField(blank=True, max_length=128)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('extra_info', models.CharField(blank=True, max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='scanning.discoveredhost')),
            ],
            options={
                'ordering': ['port_number'],
                'unique_together': {('host', 'port_number', 'protocol')},
            },
        ),
    ]
