# Generated by Django 5.0.14 on 2026-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='scan_type',
            field=models.CharField(choices=[('DISCOVERY', 'Host discovery'), ('PORT_SCAN', 'Port & service scan'), ('FULL', 'Full scan (discovery + ports + OS fingerprint)')], default='FULL', max_length=16),
        ),
        migrations.AlterField(
            model_name='target',
            name='ip_or_cidr',
            field=models.CharField(help_text='e.g. 10.0.0.15 or 10.0.0.0/24', max_length=255, verbose_name='IP or CIDR'),
        ),
    ]
