# Generated by Django 5.0.14 on 2026-08-27 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFlaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('matches_service', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], max_length=16)),
                ('remediation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CVERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=32, unique=True)),
                ('product_match', models.CharField(db_index=True, max_length=255)),
                ('version_pattern', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField()),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='MEDIUM', max_length=16)),
                ('remediation', models.TextField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='local', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['product_match'], name='vulnassess__product_a2b2eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('CVE_MATCH', 'CVE match'), ('CONFIG_FLAW', 'Configuration flaw')], default='CVE_MATCH', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], max_length=16)),
                ('risk_score', models.FloatField(help_text='0-10 composite risk score')),
                ('remediation', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('cve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='vulnassess.cverecord')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanning.scanjob')),
                ('open_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanning.openport')),
            ],
            options={
                'ordering': ['-risk_score', '-detected_at'],
                'indexes': [models.Index(fields=['severity'], name='vulnassess__severit_ac8d50_idx'), models.Index(fields=['-risk_score'], name='vulnassess__risk_sc_469ce7_idx')],
            },
        ),
    ]
