# Generated by Django 5.0.14 on 2026-09-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phone_and_sms_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totpdevice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='SMSOTPDevice',
        ),
        migrations.DeleteModel(
            name='TOTPDevice',
        ),
    ]
